name: Run ESLint on Push/PR

on:
  - push
  - pull_request

jobs:
  build:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v1

      # Install Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      # Install your dependencies
      - run: make install

      # Run ESLint
      - name: Run linter
        run: |
          make lint